// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package catalog

import (
	"context"
	"database/sql"

	"github.com/dirodriguezm/healpix"
	"github.com/dirodriguezm/xmatch/service/internal/catalog_indexer/reader"
	"github.com/dirodriguezm/xmatch/service/internal/catalog_indexer/source"
	"github.com/dirodriguezm/xmatch/service/internal/catalog_indexer/writer"
	"github.com/dirodriguezm/xmatch/service/internal/config"
	"github.com/dirodriguezm/xmatch/service/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCatalogIndexAdapter creates a new instance of MockCatalogIndexAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogIndexAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogIndexAdapter {
	mock := &MockCatalogIndexAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatalogIndexAdapter is an autogenerated mock type for the CatalogIndexAdapter type
type MockCatalogIndexAdapter struct {
	mock.Mock
}

type MockCatalogIndexAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogIndexAdapter) EXPECT() *MockCatalogIndexAdapter_Expecter {
	return &MockCatalogIndexAdapter_Expecter{mock: &_m.Mock}
}

// BulkInsertFn provides a mock function for the type MockCatalogIndexAdapter
func (_mock *MockCatalogIndexAdapter) BulkInsertFn() func(context.Context, *sql.DB, []any) error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BulkInsertFn")
	}

	var r0 func(context.Context, *sql.DB, []any) error
	if returnFunc, ok := ret.Get(0).(func() func(context.Context, *sql.DB, []any) error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(context.Context, *sql.DB, []any) error)
		}
	}
	return r0
}

// MockCatalogIndexAdapter_BulkInsertFn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkInsertFn'
type MockCatalogIndexAdapter_BulkInsertFn_Call struct {
	*mock.Call
}

// BulkInsertFn is a helper method to define mock.On call
func (_e *MockCatalogIndexAdapter_Expecter) BulkInsertFn() *MockCatalogIndexAdapter_BulkInsertFn_Call {
	return &MockCatalogIndexAdapter_BulkInsertFn_Call{Call: _e.mock.On("BulkInsertFn")}
}

func (_c *MockCatalogIndexAdapter_BulkInsertFn_Call) Run(run func()) *MockCatalogIndexAdapter_BulkInsertFn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCatalogIndexAdapter_BulkInsertFn_Call) Return(fn func(context.Context, *sql.DB, []any) error) *MockCatalogIndexAdapter_BulkInsertFn_Call {
	_c.Call.Return(fn)
	return _c
}

func (_c *MockCatalogIndexAdapter_BulkInsertFn_Call) RunAndReturn(run func() func(context.Context, *sql.DB, []any) error) *MockCatalogIndexAdapter_BulkInsertFn_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertToMastercat provides a mock function for the type MockCatalogIndexAdapter
func (_mock *MockCatalogIndexAdapter) ConvertToMastercat(raw any, mapper *healpix.HEALPixMapper) (repository.Mastercat, error) {
	ret := _mock.Called(raw, mapper)

	if len(ret) == 0 {
		panic("no return value specified for ConvertToMastercat")
	}

	var r0 repository.Mastercat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any, *healpix.HEALPixMapper) (repository.Mastercat, error)); ok {
		return returnFunc(raw, mapper)
	}
	if returnFunc, ok := ret.Get(0).(func(any, *healpix.HEALPixMapper) repository.Mastercat); ok {
		r0 = returnFunc(raw, mapper)
	} else {
		r0 = ret.Get(0).(repository.Mastercat)
	}
	if returnFunc, ok := ret.Get(1).(func(any, *healpix.HEALPixMapper) error); ok {
		r1 = returnFunc(raw, mapper)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogIndexAdapter_ConvertToMastercat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertToMastercat'
type MockCatalogIndexAdapter_ConvertToMastercat_Call struct {
	*mock.Call
}

// ConvertToMastercat is a helper method to define mock.On call
//   - raw any
//   - mapper *healpix.HEALPixMapper
func (_e *MockCatalogIndexAdapter_Expecter) ConvertToMastercat(raw interface{}, mapper interface{}) *MockCatalogIndexAdapter_ConvertToMastercat_Call {
	return &MockCatalogIndexAdapter_ConvertToMastercat_Call{Call: _e.mock.On("ConvertToMastercat", raw, mapper)}
}

func (_c *MockCatalogIndexAdapter_ConvertToMastercat_Call) Run(run func(raw any, mapper *healpix.HEALPixMapper)) *MockCatalogIndexAdapter_ConvertToMastercat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 *healpix.HEALPixMapper
		if args[1] != nil {
			arg1 = args[1].(*healpix.HEALPixMapper)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogIndexAdapter_ConvertToMastercat_Call) Return(mastercat repository.Mastercat, err error) *MockCatalogIndexAdapter_ConvertToMastercat_Call {
	_c.Call.Return(mastercat, err)
	return _c
}

func (_c *MockCatalogIndexAdapter_ConvertToMastercat_Call) RunAndReturn(run func(raw any, mapper *healpix.HEALPixMapper) (repository.Mastercat, error)) *MockCatalogIndexAdapter_ConvertToMastercat_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertToMetadataFromRaw provides a mock function for the type MockCatalogIndexAdapter
func (_mock *MockCatalogIndexAdapter) ConvertToMetadataFromRaw(raw any) (any, error) {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for ConvertToMetadataFromRaw")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) (any, error)); ok {
		return returnFunc(raw)
	}
	if returnFunc, ok := ret.Get(0).(func(any) any); ok {
		r0 = returnFunc(raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(raw)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogIndexAdapter_ConvertToMetadataFromRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertToMetadataFromRaw'
type MockCatalogIndexAdapter_ConvertToMetadataFromRaw_Call struct {
	*mock.Call
}

// ConvertToMetadataFromRaw is a helper method to define mock.On call
//   - raw any
func (_e *MockCatalogIndexAdapter_Expecter) ConvertToMetadataFromRaw(raw interface{}) *MockCatalogIndexAdapter_ConvertToMetadataFromRaw_Call {
	return &MockCatalogIndexAdapter_ConvertToMetadataFromRaw_Call{Call: _e.mock.On("ConvertToMetadataFromRaw", raw)}
}

func (_c *MockCatalogIndexAdapter_ConvertToMetadataFromRaw_Call) Run(run func(raw any)) *MockCatalogIndexAdapter_ConvertToMetadataFromRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatalogIndexAdapter_ConvertToMetadataFromRaw_Call) Return(v any, err error) *MockCatalogIndexAdapter_ConvertToMetadataFromRaw_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockCatalogIndexAdapter_ConvertToMetadataFromRaw_Call) RunAndReturn(run func(raw any) (any, error)) *MockCatalogIndexAdapter_ConvertToMetadataFromRaw_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockCatalogIndexAdapter
func (_mock *MockCatalogIndexAdapter) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCatalogIndexAdapter_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockCatalogIndexAdapter_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockCatalogIndexAdapter_Expecter) Name() *MockCatalogIndexAdapter_Name_Call {
	return &MockCatalogIndexAdapter_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockCatalogIndexAdapter_Name_Call) Run(run func()) *MockCatalogIndexAdapter_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCatalogIndexAdapter_Name_Call) Return(s string) *MockCatalogIndexAdapter_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCatalogIndexAdapter_Name_Call) RunAndReturn(run func() string) *MockCatalogIndexAdapter_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewFitsReader provides a mock function for the type MockCatalogIndexAdapter
func (_mock *MockCatalogIndexAdapter) NewFitsReader(src *source.Source, cfg config.ReaderConfig) (reader.Reader, error) {
	ret := _mock.Called(src, cfg)

	if len(ret) == 0 {
		panic("no return value specified for NewFitsReader")
	}

	var r0 reader.Reader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*source.Source, config.ReaderConfig) (reader.Reader, error)); ok {
		return returnFunc(src, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(*source.Source, config.ReaderConfig) reader.Reader); ok {
		r0 = returnFunc(src, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reader.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*source.Source, config.ReaderConfig) error); ok {
		r1 = returnFunc(src, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogIndexAdapter_NewFitsReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewFitsReader'
type MockCatalogIndexAdapter_NewFitsReader_Call struct {
	*mock.Call
}

// NewFitsReader is a helper method to define mock.On call
//   - src *source.Source
//   - cfg config.ReaderConfig
func (_e *MockCatalogIndexAdapter_Expecter) NewFitsReader(src interface{}, cfg interface{}) *MockCatalogIndexAdapter_NewFitsReader_Call {
	return &MockCatalogIndexAdapter_NewFitsReader_Call{Call: _e.mock.On("NewFitsReader", src, cfg)}
}

func (_c *MockCatalogIndexAdapter_NewFitsReader_Call) Run(run func(src *source.Source, cfg config.ReaderConfig)) *MockCatalogIndexAdapter_NewFitsReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *source.Source
		if args[0] != nil {
			arg0 = args[0].(*source.Source)
		}
		var arg1 config.ReaderConfig
		if args[1] != nil {
			arg1 = args[1].(config.ReaderConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogIndexAdapter_NewFitsReader_Call) Return(reader1 reader.Reader, err error) *MockCatalogIndexAdapter_NewFitsReader_Call {
	_c.Call.Return(reader1, err)
	return _c
}

func (_c *MockCatalogIndexAdapter_NewFitsReader_Call) RunAndReturn(run func(src *source.Source, cfg config.ReaderConfig) (reader.Reader, error)) *MockCatalogIndexAdapter_NewFitsReader_Call {
	_c.Call.Return(run)
	return _c
}

// NewParquetReader provides a mock function for the type MockCatalogIndexAdapter
func (_mock *MockCatalogIndexAdapter) NewParquetReader(src *source.Source, cfg config.ReaderConfig) (reader.Reader, error) {
	ret := _mock.Called(src, cfg)

	if len(ret) == 0 {
		panic("no return value specified for NewParquetReader")
	}

	var r0 reader.Reader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*source.Source, config.ReaderConfig) (reader.Reader, error)); ok {
		return returnFunc(src, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(*source.Source, config.ReaderConfig) reader.Reader); ok {
		r0 = returnFunc(src, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reader.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*source.Source, config.ReaderConfig) error); ok {
		r1 = returnFunc(src, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogIndexAdapter_NewParquetReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewParquetReader'
type MockCatalogIndexAdapter_NewParquetReader_Call struct {
	*mock.Call
}

// NewParquetReader is a helper method to define mock.On call
//   - src *source.Source
//   - cfg config.ReaderConfig
func (_e *MockCatalogIndexAdapter_Expecter) NewParquetReader(src interface{}, cfg interface{}) *MockCatalogIndexAdapter_NewParquetReader_Call {
	return &MockCatalogIndexAdapter_NewParquetReader_Call{Call: _e.mock.On("NewParquetReader", src, cfg)}
}

func (_c *MockCatalogIndexAdapter_NewParquetReader_Call) Run(run func(src *source.Source, cfg config.ReaderConfig)) *MockCatalogIndexAdapter_NewParquetReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *source.Source
		if args[0] != nil {
			arg0 = args[0].(*source.Source)
		}
		var arg1 config.ReaderConfig
		if args[1] != nil {
			arg1 = args[1].(config.ReaderConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogIndexAdapter_NewParquetReader_Call) Return(reader1 reader.Reader, err error) *MockCatalogIndexAdapter_NewParquetReader_Call {
	_c.Call.Return(reader1, err)
	return _c
}

func (_c *MockCatalogIndexAdapter_NewParquetReader_Call) RunAndReturn(run func(src *source.Source, cfg config.ReaderConfig) (reader.Reader, error)) *MockCatalogIndexAdapter_NewParquetReader_Call {
	_c.Call.Return(run)
	return _c
}

// NewParquetWriter provides a mock function for the type MockCatalogIndexAdapter
func (_mock *MockCatalogIndexAdapter) NewParquetWriter(cfg config.WriterConfig, ctx context.Context) (writer.Writer, error) {
	ret := _mock.Called(cfg, ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewParquetWriter")
	}

	var r0 writer.Writer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(config.WriterConfig, context.Context) (writer.Writer, error)); ok {
		return returnFunc(cfg, ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(config.WriterConfig, context.Context) writer.Writer); ok {
		r0 = returnFunc(cfg, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(writer.Writer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(config.WriterConfig, context.Context) error); ok {
		r1 = returnFunc(cfg, ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogIndexAdapter_NewParquetWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewParquetWriter'
type MockCatalogIndexAdapter_NewParquetWriter_Call struct {
	*mock.Call
}

// NewParquetWriter is a helper method to define mock.On call
//   - cfg config.WriterConfig
//   - ctx context.Context
func (_e *MockCatalogIndexAdapter_Expecter) NewParquetWriter(cfg interface{}, ctx interface{}) *MockCatalogIndexAdapter_NewParquetWriter_Call {
	return &MockCatalogIndexAdapter_NewParquetWriter_Call{Call: _e.mock.On("NewParquetWriter", cfg, ctx)}
}

func (_c *MockCatalogIndexAdapter_NewParquetWriter_Call) Run(run func(cfg config.WriterConfig, ctx context.Context)) *MockCatalogIndexAdapter_NewParquetWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.WriterConfig
		if args[0] != nil {
			arg0 = args[0].(config.WriterConfig)
		}
		var arg1 context.Context
		if args[1] != nil {
			arg1 = args[1].(context.Context)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogIndexAdapter_NewParquetWriter_Call) Return(writer1 writer.Writer, err error) *MockCatalogIndexAdapter_NewParquetWriter_Call {
	_c.Call.Return(writer1, err)
	return _c
}

func (_c *MockCatalogIndexAdapter_NewParquetWriter_Call) RunAndReturn(run func(cfg config.WriterConfig, ctx context.Context) (writer.Writer, error)) *MockCatalogIndexAdapter_NewParquetWriter_Call {
	_c.Call.Return(run)
	return _c
}

// NewRawRecord provides a mock function for the type MockCatalogIndexAdapter
func (_mock *MockCatalogIndexAdapter) NewRawRecord() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewRawRecord")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockCatalogIndexAdapter_NewRawRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRawRecord'
type MockCatalogIndexAdapter_NewRawRecord_Call struct {
	*mock.Call
}

// NewRawRecord is a helper method to define mock.On call
func (_e *MockCatalogIndexAdapter_Expecter) NewRawRecord() *MockCatalogIndexAdapter_NewRawRecord_Call {
	return &MockCatalogIndexAdapter_NewRawRecord_Call{Call: _e.mock.On("NewRawRecord")}
}

func (_c *MockCatalogIndexAdapter_NewRawRecord_Call) Run(run func()) *MockCatalogIndexAdapter_NewRawRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCatalogIndexAdapter_NewRawRecord_Call) Return(v any) *MockCatalogIndexAdapter_NewRawRecord_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockCatalogIndexAdapter_NewRawRecord_Call) RunAndReturn(run func() any) *MockCatalogIndexAdapter_NewRawRecord_Call {
	_c.Call.Return(run)
	return _c
}
