// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package catalog

import (
	"context"

	"github.com/dirodriguezm/xmatch/service/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCatalogAdapter creates a new instance of MockCatalogAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogAdapter {
	mock := &MockCatalogAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatalogAdapter is an autogenerated mock type for the CatalogAdapter type
type MockCatalogAdapter struct {
	mock.Mock
}

type MockCatalogAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogAdapter) EXPECT() *MockCatalogAdapter_Expecter {
	return &MockCatalogAdapter_Expecter{mock: &_m.Mock}
}

// BulkGetByID provides a mock function for the type MockCatalogAdapter
func (_mock *MockCatalogAdapter) BulkGetByID(ctx context.Context, ids []string) (any, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkGetByID")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (any, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) any); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogAdapter_BulkGetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGetByID'
type MockCatalogAdapter_BulkGetByID_Call struct {
	*mock.Call
}

// BulkGetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockCatalogAdapter_Expecter) BulkGetByID(ctx interface{}, ids interface{}) *MockCatalogAdapter_BulkGetByID_Call {
	return &MockCatalogAdapter_BulkGetByID_Call{Call: _e.mock.On("BulkGetByID", ctx, ids)}
}

func (_c *MockCatalogAdapter_BulkGetByID_Call) Run(run func(ctx context.Context, ids []string)) *MockCatalogAdapter_BulkGetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogAdapter_BulkGetByID_Call) Return(v any, err error) *MockCatalogAdapter_BulkGetByID_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockCatalogAdapter_BulkGetByID_Call) RunAndReturn(run func(ctx context.Context, ids []string) (any, error)) *MockCatalogAdapter_BulkGetByID_Call {
	_c.Call.Return(run)
	return _c
}

// BulkInsertMetadata provides a mock function for the type MockCatalogAdapter
func (_mock *MockCatalogAdapter) BulkInsertMetadata(ctx context.Context, rows []any) error {
	ret := _mock.Called(ctx, rows)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsertMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []any) error); ok {
		r0 = returnFunc(ctx, rows)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatalogAdapter_BulkInsertMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkInsertMetadata'
type MockCatalogAdapter_BulkInsertMetadata_Call struct {
	*mock.Call
}

// BulkInsertMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - rows []any
func (_e *MockCatalogAdapter_Expecter) BulkInsertMetadata(ctx interface{}, rows interface{}) *MockCatalogAdapter_BulkInsertMetadata_Call {
	return &MockCatalogAdapter_BulkInsertMetadata_Call{Call: _e.mock.On("BulkInsertMetadata", ctx, rows)}
}

func (_c *MockCatalogAdapter_BulkInsertMetadata_Call) Run(run func(ctx context.Context, rows []any)) *MockCatalogAdapter_BulkInsertMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []any
		if args[1] != nil {
			arg1 = args[1].([]any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogAdapter_BulkInsertMetadata_Call) Return(err error) *MockCatalogAdapter_BulkInsertMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatalogAdapter_BulkInsertMetadata_Call) RunAndReturn(run func(ctx context.Context, rows []any) error) *MockCatalogAdapter_BulkInsertMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertToMastercat provides a mock function for the type MockCatalogAdapter
func (_mock *MockCatalogAdapter) ConvertToMastercat(raw any, ipix int64) (repository.Mastercat, error) {
	ret := _mock.Called(raw, ipix)

	if len(ret) == 0 {
		panic("no return value specified for ConvertToMastercat")
	}

	var r0 repository.Mastercat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any, int64) (repository.Mastercat, error)); ok {
		return returnFunc(raw, ipix)
	}
	if returnFunc, ok := ret.Get(0).(func(any, int64) repository.Mastercat); ok {
		r0 = returnFunc(raw, ipix)
	} else {
		r0 = ret.Get(0).(repository.Mastercat)
	}
	if returnFunc, ok := ret.Get(1).(func(any, int64) error); ok {
		r1 = returnFunc(raw, ipix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogAdapter_ConvertToMastercat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertToMastercat'
type MockCatalogAdapter_ConvertToMastercat_Call struct {
	*mock.Call
}

// ConvertToMastercat is a helper method to define mock.On call
//   - raw any
//   - ipix int64
func (_e *MockCatalogAdapter_Expecter) ConvertToMastercat(raw interface{}, ipix interface{}) *MockCatalogAdapter_ConvertToMastercat_Call {
	return &MockCatalogAdapter_ConvertToMastercat_Call{Call: _e.mock.On("ConvertToMastercat", raw, ipix)}
}

func (_c *MockCatalogAdapter_ConvertToMastercat_Call) Run(run func(raw any, ipix int64)) *MockCatalogAdapter_ConvertToMastercat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogAdapter_ConvertToMastercat_Call) Return(mastercat repository.Mastercat, err error) *MockCatalogAdapter_ConvertToMastercat_Call {
	_c.Call.Return(mastercat, err)
	return _c
}

func (_c *MockCatalogAdapter_ConvertToMastercat_Call) RunAndReturn(run func(raw any, ipix int64) (repository.Mastercat, error)) *MockCatalogAdapter_ConvertToMastercat_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertToMetadataFromRaw provides a mock function for the type MockCatalogAdapter
func (_mock *MockCatalogAdapter) ConvertToMetadataFromRaw(raw any) (any, error) {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for ConvertToMetadataFromRaw")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) (any, error)); ok {
		return returnFunc(raw)
	}
	if returnFunc, ok := ret.Get(0).(func(any) any); ok {
		r0 = returnFunc(raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(raw)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogAdapter_ConvertToMetadataFromRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertToMetadataFromRaw'
type MockCatalogAdapter_ConvertToMetadataFromRaw_Call struct {
	*mock.Call
}

// ConvertToMetadataFromRaw is a helper method to define mock.On call
//   - raw any
func (_e *MockCatalogAdapter_Expecter) ConvertToMetadataFromRaw(raw interface{}) *MockCatalogAdapter_ConvertToMetadataFromRaw_Call {
	return &MockCatalogAdapter_ConvertToMetadataFromRaw_Call{Call: _e.mock.On("ConvertToMetadataFromRaw", raw)}
}

func (_c *MockCatalogAdapter_ConvertToMetadataFromRaw_Call) Run(run func(raw any)) *MockCatalogAdapter_ConvertToMetadataFromRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatalogAdapter_ConvertToMetadataFromRaw_Call) Return(v any, err error) *MockCatalogAdapter_ConvertToMetadataFromRaw_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockCatalogAdapter_ConvertToMetadataFromRaw_Call) RunAndReturn(run func(raw any) (any, error)) *MockCatalogAdapter_ConvertToMetadataFromRaw_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCatalogAdapter
func (_mock *MockCatalogAdapter) GetByID(ctx context.Context, id string) (any, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (any, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) any); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogAdapter_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCatalogAdapter_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCatalogAdapter_Expecter) GetByID(ctx interface{}, id interface{}) *MockCatalogAdapter_GetByID_Call {
	return &MockCatalogAdapter_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCatalogAdapter_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockCatalogAdapter_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogAdapter_GetByID_Call) Return(v any, err error) *MockCatalogAdapter_GetByID_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockCatalogAdapter_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (any, error)) *MockCatalogAdapter_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoordinates provides a mock function for the type MockCatalogAdapter
func (_mock *MockCatalogAdapter) GetCoordinates(raw any) (float64, float64, error) {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for GetCoordinates")
	}

	var r0 float64
	var r1 float64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(any) (float64, float64, error)); ok {
		return returnFunc(raw)
	}
	if returnFunc, ok := ret.Get(0).(func(any) float64); ok {
		r0 = returnFunc(raw)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(any) float64); ok {
		r1 = returnFunc(raw)
	} else {
		r1 = ret.Get(1).(float64)
	}
	if returnFunc, ok := ret.Get(2).(func(any) error); ok {
		r2 = returnFunc(raw)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCatalogAdapter_GetCoordinates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoordinates'
type MockCatalogAdapter_GetCoordinates_Call struct {
	*mock.Call
}

// GetCoordinates is a helper method to define mock.On call
//   - raw any
func (_e *MockCatalogAdapter_Expecter) GetCoordinates(raw interface{}) *MockCatalogAdapter_GetCoordinates_Call {
	return &MockCatalogAdapter_GetCoordinates_Call{Call: _e.mock.On("GetCoordinates", raw)}
}

func (_c *MockCatalogAdapter_GetCoordinates_Call) Run(run func(raw any)) *MockCatalogAdapter_GetCoordinates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatalogAdapter_GetCoordinates_Call) Return(f float64, f1 float64, err error) *MockCatalogAdapter_GetCoordinates_Call {
	_c.Call.Return(f, f1, err)
	return _c
}

func (_c *MockCatalogAdapter_GetCoordinates_Call) RunAndReturn(run func(raw any) (float64, float64, error)) *MockCatalogAdapter_GetCoordinates_Call {
	_c.Call.Return(run)
	return _c
}

// GetFromPixels provides a mock function for the type MockCatalogAdapter
func (_mock *MockCatalogAdapter) GetFromPixels(ctx context.Context, pixels []int64) ([]repository.Metadata, error) {
	ret := _mock.Called(ctx, pixels)

	if len(ret) == 0 {
		panic("no return value specified for GetFromPixels")
	}

	var r0 []repository.Metadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]repository.Metadata, error)); ok {
		return returnFunc(ctx, pixels)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []repository.Metadata); ok {
		r0 = returnFunc(ctx, pixels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Metadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, pixels)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogAdapter_GetFromPixels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFromPixels'
type MockCatalogAdapter_GetFromPixels_Call struct {
	*mock.Call
}

// GetFromPixels is a helper method to define mock.On call
//   - ctx context.Context
//   - pixels []int64
func (_e *MockCatalogAdapter_Expecter) GetFromPixels(ctx interface{}, pixels interface{}) *MockCatalogAdapter_GetFromPixels_Call {
	return &MockCatalogAdapter_GetFromPixels_Call{Call: _e.mock.On("GetFromPixels", ctx, pixels)}
}

func (_c *MockCatalogAdapter_GetFromPixels_Call) Run(run func(ctx context.Context, pixels []int64)) *MockCatalogAdapter_GetFromPixels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogAdapter_GetFromPixels_Call) Return(metadatas []repository.Metadata, err error) *MockCatalogAdapter_GetFromPixels_Call {
	_c.Call.Return(metadatas, err)
	return _c
}

func (_c *MockCatalogAdapter_GetFromPixels_Call) RunAndReturn(run func(ctx context.Context, pixels []int64) ([]repository.Metadata, error)) *MockCatalogAdapter_GetFromPixels_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockCatalogAdapter
func (_mock *MockCatalogAdapter) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCatalogAdapter_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockCatalogAdapter_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockCatalogAdapter_Expecter) Name() *MockCatalogAdapter_Name_Call {
	return &MockCatalogAdapter_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockCatalogAdapter_Name_Call) Run(run func()) *MockCatalogAdapter_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCatalogAdapter_Name_Call) Return(s string) *MockCatalogAdapter_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCatalogAdapter_Name_Call) RunAndReturn(run func() string) *MockCatalogAdapter_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMetadataRecord provides a mock function for the type MockCatalogAdapter
func (_mock *MockCatalogAdapter) NewMetadataRecord() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewMetadataRecord")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockCatalogAdapter_NewMetadataRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewMetadataRecord'
type MockCatalogAdapter_NewMetadataRecord_Call struct {
	*mock.Call
}

// NewMetadataRecord is a helper method to define mock.On call
func (_e *MockCatalogAdapter_Expecter) NewMetadataRecord() *MockCatalogAdapter_NewMetadataRecord_Call {
	return &MockCatalogAdapter_NewMetadataRecord_Call{Call: _e.mock.On("NewMetadataRecord")}
}

func (_c *MockCatalogAdapter_NewMetadataRecord_Call) Run(run func()) *MockCatalogAdapter_NewMetadataRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCatalogAdapter_NewMetadataRecord_Call) Return(v any) *MockCatalogAdapter_NewMetadataRecord_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockCatalogAdapter_NewMetadataRecord_Call) RunAndReturn(run func() any) *MockCatalogAdapter_NewMetadataRecord_Call {
	_c.Call.Return(run)
	return _c
}

// NewRawRecord provides a mock function for the type MockCatalogAdapter
func (_mock *MockCatalogAdapter) NewRawRecord() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewRawRecord")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockCatalogAdapter_NewRawRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRawRecord'
type MockCatalogAdapter_NewRawRecord_Call struct {
	*mock.Call
}

// NewRawRecord is a helper method to define mock.On call
func (_e *MockCatalogAdapter_Expecter) NewRawRecord() *MockCatalogAdapter_NewRawRecord_Call {
	return &MockCatalogAdapter_NewRawRecord_Call{Call: _e.mock.On("NewRawRecord")}
}

func (_c *MockCatalogAdapter_NewRawRecord_Call) Run(run func()) *MockCatalogAdapter_NewRawRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCatalogAdapter_NewRawRecord_Call) Return(v any) *MockCatalogAdapter_NewRawRecord_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockCatalogAdapter_NewRawRecord_Call) RunAndReturn(run func() any) *MockCatalogAdapter_NewRawRecord_Call {
	_c.Call.Return(run)
	return _c
}
