// Code generated by mockery; DO NOT EDIT.

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

func NewMockMastercatReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMastercatReader {
	m := &MockMastercatReader{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

type MockMastercatReader struct {
	mock.Mock
}

func (m *MockMastercatReader) FindObjects(ctx context.Context, ipix []int64) ([]Mastercat, error) {
	ret := m.Called(ctx, ipix)

	if len(ret) == 0 {
		panic("no return value specified for FindObjects")
	}

	var r0 []Mastercat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]Mastercat, error)); ok {
		return returnFunc(ctx, ipix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []Mastercat); ok {
		r0 = returnFunc(ctx, ipix)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]Mastercat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, ipix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func NewMockMastercatWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMastercatWriter {
	m := &MockMastercatWriter{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

type MockMastercatWriter struct {
	mock.Mock
}

func (m *MockMastercatWriter) BulkInsertObject(ctx context.Context, rows []any) error {
	ret := m.Called(ctx, rows)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsertObject")
	}

	if returnFunc, ok := ret.Get(0).(func(context.Context, []any) error); ok {
		return returnFunc(ctx, rows)
	}
	return ret.Error(0)
}
