// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/dirodriguezm/healpix"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMastercatReader creates a new instance of MockMastercatReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMastercatReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMastercatReader {
	mock := &MockMastercatReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMastercatReader is an autogenerated mock type for the MastercatReader type
type MockMastercatReader struct {
	mock.Mock
}

type MockMastercatReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMastercatReader) EXPECT() *MockMastercatReader_Expecter {
	return &MockMastercatReader_Expecter{mock: &_m.Mock}
}

// FindObjectsInPixelRanges provides a mock function for the type MockMastercatReader
func (_mock *MockMastercatReader) FindObjectsInPixelRanges(context1 context.Context, pixelRanges []healpix.PixelRange) ([]Mastercat, error) {
	ret := _mock.Called(context1, pixelRanges)

	if len(ret) == 0 {
		panic("no return value specified for FindObjectsInPixelRanges")
	}

	var r0 []Mastercat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []healpix.PixelRange) ([]Mastercat, error)); ok {
		return returnFunc(context1, pixelRanges)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []healpix.PixelRange) []Mastercat); ok {
		r0 = returnFunc(context1, pixelRanges)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Mastercat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []healpix.PixelRange) error); ok {
		r1 = returnFunc(context1, pixelRanges)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMastercatReader_FindObjectsInPixelRanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindObjectsInPixelRanges'
type MockMastercatReader_FindObjectsInPixelRanges_Call struct {
	*mock.Call
}

// FindObjectsInPixelRanges is a helper method to define mock.On call
//   - context1 context.Context
//   - pixelRanges []healpix.PixelRange
func (_e *MockMastercatReader_Expecter) FindObjectsInPixelRanges(context1 interface{}, pixelRanges interface{}) *MockMastercatReader_FindObjectsInPixelRanges_Call {
	return &MockMastercatReader_FindObjectsInPixelRanges_Call{Call: _e.mock.On("FindObjectsInPixelRanges", context1, pixelRanges)}
}

func (_c *MockMastercatReader_FindObjectsInPixelRanges_Call) Run(run func(context1 context.Context, pixelRanges []healpix.PixelRange)) *MockMastercatReader_FindObjectsInPixelRanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []healpix.PixelRange
		if args[1] != nil {
			arg1 = args[1].([]healpix.PixelRange)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMastercatReader_FindObjectsInPixelRanges_Call) Return(mastercats []Mastercat, err error) *MockMastercatReader_FindObjectsInPixelRanges_Call {
	_c.Call.Return(mastercats, err)
	return _c
}

func (_c *MockMastercatReader_FindObjectsInPixelRanges_Call) RunAndReturn(run func(context1 context.Context, pixelRanges []healpix.PixelRange) ([]Mastercat, error)) *MockMastercatReader_FindObjectsInPixelRanges_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMastercatWriter creates a new instance of MockMastercatWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMastercatWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMastercatWriter {
	mock := &MockMastercatWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMastercatWriter is an autogenerated mock type for the MastercatWriter type
type MockMastercatWriter struct {
	mock.Mock
}

type MockMastercatWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMastercatWriter) EXPECT() *MockMastercatWriter_Expecter {
	return &MockMastercatWriter_Expecter{mock: &_m.Mock}
}

// BulkInsertObject provides a mock function for the type MockMastercatWriter
func (_mock *MockMastercatWriter) BulkInsertObject(context1 context.Context, vs []any) error {
	ret := _mock.Called(context1, vs)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsertObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []any) error); ok {
		r0 = returnFunc(context1, vs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMastercatWriter_BulkInsertObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkInsertObject'
type MockMastercatWriter_BulkInsertObject_Call struct {
	*mock.Call
}

// BulkInsertObject is a helper method to define mock.On call
//   - context1 context.Context
//   - vs []any
func (_e *MockMastercatWriter_Expecter) BulkInsertObject(context1 interface{}, vs interface{}) *MockMastercatWriter_BulkInsertObject_Call {
	return &MockMastercatWriter_BulkInsertObject_Call{Call: _e.mock.On("BulkInsertObject", context1, vs)}
}

func (_c *MockMastercatWriter_BulkInsertObject_Call) Run(run func(context1 context.Context, vs []any)) *MockMastercatWriter_BulkInsertObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []any
		if args[1] != nil {
			arg1 = args[1].([]any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMastercatWriter_BulkInsertObject_Call) Return(err error) *MockMastercatWriter_BulkInsertObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMastercatWriter_BulkInsertObject_Call) RunAndReturn(run func(context1 context.Context, vs []any) error) *MockMastercatWriter_BulkInsertObject_Call {
	_c.Call.Return(run)
	return _c
}
