// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package repository

import (
	"context"
	"database/sql"
	"strings"
)

const findObjects = `-- name: FindObjects :many
SELECT id, ipix, ra, dec, cat
FROM mastercat 
WHERE ipix IN (/*SLICE:ipix*/?)
`

func (q *Queries) FindObjects(ctx context.Context, ipix []int64) ([]Mastercat, error) {
	query := findObjects
	var queryParams []interface{}
	if len(ipix) > 0 {
		for _, v := range ipix {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ipix*/?", strings.Repeat(",?", len(ipix))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ipix*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mastercat
	for rows.Next() {
		var i Mastercat
		if err := rows.Scan(
			&i.ID,
			&i.Ipix,
			&i.Ra,
			&i.Dec,
			&i.Cat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllObjects = `-- name: GetAllObjects :many
SELECT id, ipix, ra, dec, cat
FROM mastercat
`

func (q *Queries) GetAllObjects(ctx context.Context) ([]Mastercat, error) {
	rows, err := q.db.QueryContext(ctx, getAllObjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mastercat
	for rows.Next() {
		var i Mastercat
		if err := rows.Scan(
			&i.ID,
			&i.Ipix,
			&i.Ra,
			&i.Dec,
			&i.Cat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllwise = `-- name: GetAllwise :many
SELECT id, w1mpro, w1sigmpro, w2mpro, w2sigmpro, w3mpro, w3sigmpro, w4mpro, w4sigmpro, j_m_2mass, j_msig_2mass, h_m_2mass, h_msig_2mass, k_m_2mass, k_msig_2mass
FROM allwise
WHERE id = ?
`

func (q *Queries) GetAllwise(ctx context.Context, id string) ([]Allwise, error) {
	rows, err := q.db.QueryContext(ctx, getAllwise, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Allwise
	for rows.Next() {
		var i Allwise
		if err := rows.Scan(
			&i.ID,
			&i.W1mpro,
			&i.W1sigmpro,
			&i.W2mpro,
			&i.W2sigmpro,
			&i.W3mpro,
			&i.W3sigmpro,
			&i.W4mpro,
			&i.W4sigmpro,
			&i.JM2mass,
			&i.JMsig2mass,
			&i.HM2mass,
			&i.HMsig2mass,
			&i.KM2mass,
			&i.KMsig2mass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCatalogs = `-- name: GetCatalogs :many
SELECT name, nside
FROM catalogs
`

func (q *Queries) GetCatalogs(ctx context.Context) ([]Catalog, error) {
	rows, err := q.db.QueryContext(ctx, getCatalogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Catalog
	for rows.Next() {
		var i Catalog
		if err := rows.Scan(&i.Name, &i.Nside); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectsFromCatalog = `-- name: GetObjectsFromCatalog :many
SELECT id, ipix, ra, dec, cat 
FROM mastercat 
WHERE ipix IN (/*SLICE:ipix*/?)
AND cat = ?
`

type GetObjectsFromCatalogParams struct {
	Ipix []int64
	Cat  string
}

func (q *Queries) GetObjectsFromCatalog(ctx context.Context, arg GetObjectsFromCatalogParams) ([]Mastercat, error) {
	query := getObjectsFromCatalog
	var queryParams []interface{}
	if len(arg.Ipix) > 0 {
		for _, v := range arg.Ipix {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ipix*/?", strings.Repeat(",?", len(arg.Ipix))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ipix*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Cat)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mastercat
	for rows.Next() {
		var i Mastercat
		if err := rows.Scan(
			&i.ID,
			&i.Ipix,
			&i.Ra,
			&i.Dec,
			&i.Cat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAllwise = `-- name: InsertAllwise :exec
INSERT INTO allwise (
	id, w1mpro, w1sigmpro, w2mpro, w2sigmpro, w3mpro, w3sigmpro, w4mpro, w4sigmpro, J_m_2mass, J_msig_2mass, H_m_2mass, H_msig_2mass, K_m_2mass, K_msig_2mass
) VALUES (
	?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertAllwiseParams struct {
	ID         string
	W1mpro     sql.NullFloat64
	W1sigmpro  sql.NullFloat64
	W2mpro     sql.NullFloat64
	W2sigmpro  sql.NullFloat64
	W3mpro     sql.NullFloat64
	W3sigmpro  sql.NullFloat64
	W4mpro     sql.NullFloat64
	W4sigmpro  sql.NullFloat64
	JM2mass    sql.NullFloat64
	JMsig2mass sql.NullFloat64
	HM2mass    sql.NullFloat64
	HMsig2mass sql.NullFloat64
	KM2mass    sql.NullFloat64
	KMsig2mass sql.NullFloat64
}

func (q *Queries) InsertAllwise(ctx context.Context, arg InsertAllwiseParams) error {
	_, err := q.db.ExecContext(ctx, insertAllwise,
		arg.ID,
		arg.W1mpro,
		arg.W1sigmpro,
		arg.W2mpro,
		arg.W2sigmpro,
		arg.W3mpro,
		arg.W3sigmpro,
		arg.W4mpro,
		arg.W4sigmpro,
		arg.JM2mass,
		arg.JMsig2mass,
		arg.HM2mass,
		arg.HMsig2mass,
		arg.KM2mass,
		arg.KMsig2mass,
	)
	return err
}

const insertCatalog = `-- name: InsertCatalog :one
INSERT INTO catalogs (
	name, nside
) VALUES (
	?, ?
)
RETURNING name, nside
`

type InsertCatalogParams struct {
	Name  string
	Nside int64
}

func (q *Queries) InsertCatalog(ctx context.Context, arg InsertCatalogParams) (Catalog, error) {
	row := q.db.QueryRowContext(ctx, insertCatalog, arg.Name, arg.Nside)
	var i Catalog
	err := row.Scan(&i.Name, &i.Nside)
	return i, err
}

const insertObject = `-- name: InsertObject :one
INSERT INTO mastercat (
	id, ipix, ra, dec, cat
) VALUES (
	?, ?, ?, ?, ?
)
RETURNING id, ipix, ra, dec, cat
`

type InsertObjectParams struct {
	ID   string
	Ipix int64
	Ra   float64
	Dec  float64
	Cat  string
}

func (q *Queries) InsertObject(ctx context.Context, arg InsertObjectParams) (Mastercat, error) {
	row := q.db.QueryRowContext(ctx, insertObject,
		arg.ID,
		arg.Ipix,
		arg.Ra,
		arg.Dec,
		arg.Cat,
	)
	var i Mastercat
	err := row.Scan(
		&i.ID,
		&i.Ipix,
		&i.Ra,
		&i.Dec,
		&i.Cat,
	)
	return i, err
}
