// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/dirodriguezm/xmatch/service/internal/repository"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// BulkInsertAllwise provides a mock function with given fields: _a0, _a1, _a2
func (_m *Repository) BulkInsertAllwise(_a0 context.Context, _a1 *sql.DB, _a2 []repository.InsertAllwiseParams) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsertAllwise")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.DB, []repository.InsertAllwiseParams) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_BulkInsertAllwise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkInsertAllwise'
type Repository_BulkInsertAllwise_Call struct {
	*mock.Call
}

// BulkInsertAllwise is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *sql.DB
//   - _a2 []repository.InsertAllwiseParams
func (_e *Repository_Expecter) BulkInsertAllwise(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Repository_BulkInsertAllwise_Call {
	return &Repository_BulkInsertAllwise_Call{Call: _e.mock.On("BulkInsertAllwise", _a0, _a1, _a2)}
}

func (_c *Repository_BulkInsertAllwise_Call) Run(run func(_a0 context.Context, _a1 *sql.DB, _a2 []repository.InsertAllwiseParams)) *Repository_BulkInsertAllwise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.DB), args[2].([]repository.InsertAllwiseParams))
	})
	return _c
}

func (_c *Repository_BulkInsertAllwise_Call) Return(_a0 error) *Repository_BulkInsertAllwise_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_BulkInsertAllwise_Call) RunAndReturn(run func(context.Context, *sql.DB, []repository.InsertAllwiseParams) error) *Repository_BulkInsertAllwise_Call {
	_c.Call.Return(run)
	return _c
}

// BulkInsertObject provides a mock function with given fields: _a0, _a1, _a2
func (_m *Repository) BulkInsertObject(_a0 context.Context, _a1 *sql.DB, _a2 []repository.InsertObjectParams) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsertObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.DB, []repository.InsertObjectParams) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_BulkInsertObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkInsertObject'
type Repository_BulkInsertObject_Call struct {
	*mock.Call
}

// BulkInsertObject is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *sql.DB
//   - _a2 []repository.InsertObjectParams
func (_e *Repository_Expecter) BulkInsertObject(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Repository_BulkInsertObject_Call {
	return &Repository_BulkInsertObject_Call{Call: _e.mock.On("BulkInsertObject", _a0, _a1, _a2)}
}

func (_c *Repository_BulkInsertObject_Call) Run(run func(_a0 context.Context, _a1 *sql.DB, _a2 []repository.InsertObjectParams)) *Repository_BulkInsertObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.DB), args[2].([]repository.InsertObjectParams))
	})
	return _c
}

func (_c *Repository_BulkInsertObject_Call) Return(_a0 error) *Repository_BulkInsertObject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_BulkInsertObject_Call) RunAndReturn(run func(context.Context, *sql.DB, []repository.InsertObjectParams) error) *Repository_BulkInsertObject_Call {
	_c.Call.Return(run)
	return _c
}

// FindObjects provides a mock function with given fields: _a0, _a1
func (_m *Repository) FindObjects(_a0 context.Context, _a1 []int64) ([]repository.Mastercat, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindObjects")
	}

	var r0 []repository.Mastercat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]repository.Mastercat, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []repository.Mastercat); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Mastercat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindObjects'
type Repository_FindObjects_Call struct {
	*mock.Call
}

// FindObjects is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []int64
func (_e *Repository_Expecter) FindObjects(_a0 interface{}, _a1 interface{}) *Repository_FindObjects_Call {
	return &Repository_FindObjects_Call{Call: _e.mock.On("FindObjects", _a0, _a1)}
}

func (_c *Repository_FindObjects_Call) Run(run func(_a0 context.Context, _a1 []int64)) *Repository_FindObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *Repository_FindObjects_Call) Return(_a0 []repository.Mastercat, _a1 error) *Repository_FindObjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindObjects_Call) RunAndReturn(run func(context.Context, []int64) ([]repository.Mastercat, error)) *Repository_FindObjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllObjects provides a mock function with given fields: _a0
func (_m *Repository) GetAllObjects(_a0 context.Context) ([]repository.Mastercat, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAllObjects")
	}

	var r0 []repository.Mastercat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]repository.Mastercat, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []repository.Mastercat); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Mastercat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetAllObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllObjects'
type Repository_GetAllObjects_Call struct {
	*mock.Call
}

// GetAllObjects is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Repository_Expecter) GetAllObjects(_a0 interface{}) *Repository_GetAllObjects_Call {
	return &Repository_GetAllObjects_Call{Call: _e.mock.On("GetAllObjects", _a0)}
}

func (_c *Repository_GetAllObjects_Call) Run(run func(_a0 context.Context)) *Repository_GetAllObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_GetAllObjects_Call) Return(_a0 []repository.Mastercat, _a1 error) *Repository_GetAllObjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetAllObjects_Call) RunAndReturn(run func(context.Context) ([]repository.Mastercat, error)) *Repository_GetAllObjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllwise provides a mock function with given fields: _a0, _a1
func (_m *Repository) GetAllwise(_a0 context.Context, _a1 string) (repository.Allwise, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAllwise")
	}

	var r0 repository.Allwise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repository.Allwise, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.Allwise); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(repository.Allwise)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetAllwise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllwise'
type Repository_GetAllwise_Call struct {
	*mock.Call
}

// GetAllwise is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *Repository_Expecter) GetAllwise(_a0 interface{}, _a1 interface{}) *Repository_GetAllwise_Call {
	return &Repository_GetAllwise_Call{Call: _e.mock.On("GetAllwise", _a0, _a1)}
}

func (_c *Repository_GetAllwise_Call) Run(run func(_a0 context.Context, _a1 string)) *Repository_GetAllwise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_GetAllwise_Call) Return(_a0 repository.Allwise, _a1 error) *Repository_GetAllwise_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetAllwise_Call) RunAndReturn(run func(context.Context, string) (repository.Allwise, error)) *Repository_GetAllwise_Call {
	_c.Call.Return(run)
	return _c
}

// GetCatalogs provides a mock function with given fields: _a0
func (_m *Repository) GetCatalogs(_a0 context.Context) ([]repository.Catalog, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetCatalogs")
	}

	var r0 []repository.Catalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]repository.Catalog, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []repository.Catalog); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Catalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetCatalogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCatalogs'
type Repository_GetCatalogs_Call struct {
	*mock.Call
}

// GetCatalogs is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Repository_Expecter) GetCatalogs(_a0 interface{}) *Repository_GetCatalogs_Call {
	return &Repository_GetCatalogs_Call{Call: _e.mock.On("GetCatalogs", _a0)}
}

func (_c *Repository_GetCatalogs_Call) Run(run func(_a0 context.Context)) *Repository_GetCatalogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_GetCatalogs_Call) Return(_a0 []repository.Catalog, _a1 error) *Repository_GetCatalogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetCatalogs_Call) RunAndReturn(run func(context.Context) ([]repository.Catalog, error)) *Repository_GetCatalogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetDbInstance provides a mock function with no fields
func (_m *Repository) GetDbInstance() *sql.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDbInstance")
	}

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}

// Repository_GetDbInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDbInstance'
type Repository_GetDbInstance_Call struct {
	*mock.Call
}

// GetDbInstance is a helper method to define mock.On call
func (_e *Repository_Expecter) GetDbInstance() *Repository_GetDbInstance_Call {
	return &Repository_GetDbInstance_Call{Call: _e.mock.On("GetDbInstance")}
}

func (_c *Repository_GetDbInstance_Call) Run(run func()) *Repository_GetDbInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_GetDbInstance_Call) Return(_a0 *sql.DB) *Repository_GetDbInstance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_GetDbInstance_Call) RunAndReturn(run func() *sql.DB) *Repository_GetDbInstance_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAllwise provides a mock function with given fields: _a0, _a1
func (_m *Repository) InsertAllwise(_a0 context.Context, _a1 repository.InsertAllwiseParams) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertAllwise")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.InsertAllwiseParams) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_InsertAllwise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAllwise'
type Repository_InsertAllwise_Call struct {
	*mock.Call
}

// InsertAllwise is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repository.InsertAllwiseParams
func (_e *Repository_Expecter) InsertAllwise(_a0 interface{}, _a1 interface{}) *Repository_InsertAllwise_Call {
	return &Repository_InsertAllwise_Call{Call: _e.mock.On("InsertAllwise", _a0, _a1)}
}

func (_c *Repository_InsertAllwise_Call) Run(run func(_a0 context.Context, _a1 repository.InsertAllwiseParams)) *Repository_InsertAllwise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.InsertAllwiseParams))
	})
	return _c
}

func (_c *Repository_InsertAllwise_Call) Return(_a0 error) *Repository_InsertAllwise_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_InsertAllwise_Call) RunAndReturn(run func(context.Context, repository.InsertAllwiseParams) error) *Repository_InsertAllwise_Call {
	_c.Call.Return(run)
	return _c
}

// InsertCatalog provides a mock function with given fields: _a0, _a1
func (_m *Repository) InsertCatalog(_a0 context.Context, _a1 repository.InsertCatalogParams) (repository.Catalog, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertCatalog")
	}

	var r0 repository.Catalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.InsertCatalogParams) (repository.Catalog, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.InsertCatalogParams) repository.Catalog); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(repository.Catalog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.InsertCatalogParams) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_InsertCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertCatalog'
type Repository_InsertCatalog_Call struct {
	*mock.Call
}

// InsertCatalog is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repository.InsertCatalogParams
func (_e *Repository_Expecter) InsertCatalog(_a0 interface{}, _a1 interface{}) *Repository_InsertCatalog_Call {
	return &Repository_InsertCatalog_Call{Call: _e.mock.On("InsertCatalog", _a0, _a1)}
}

func (_c *Repository_InsertCatalog_Call) Run(run func(_a0 context.Context, _a1 repository.InsertCatalogParams)) *Repository_InsertCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.InsertCatalogParams))
	})
	return _c
}

func (_c *Repository_InsertCatalog_Call) Return(_a0 repository.Catalog, _a1 error) *Repository_InsertCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_InsertCatalog_Call) RunAndReturn(run func(context.Context, repository.InsertCatalogParams) (repository.Catalog, error)) *Repository_InsertCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// InsertObject provides a mock function with given fields: _a0, _a1
func (_m *Repository) InsertObject(_a0 context.Context, _a1 repository.InsertObjectParams) (repository.Mastercat, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertObject")
	}

	var r0 repository.Mastercat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.InsertObjectParams) (repository.Mastercat, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.InsertObjectParams) repository.Mastercat); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(repository.Mastercat)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.InsertObjectParams) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_InsertObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertObject'
type Repository_InsertObject_Call struct {
	*mock.Call
}

// InsertObject is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repository.InsertObjectParams
func (_e *Repository_Expecter) InsertObject(_a0 interface{}, _a1 interface{}) *Repository_InsertObject_Call {
	return &Repository_InsertObject_Call{Call: _e.mock.On("InsertObject", _a0, _a1)}
}

func (_c *Repository_InsertObject_Call) Run(run func(_a0 context.Context, _a1 repository.InsertObjectParams)) *Repository_InsertObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.InsertObjectParams))
	})
	return _c
}

func (_c *Repository_InsertObject_Call) Return(_a0 repository.Mastercat, _a1 error) *Repository_InsertObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_InsertObject_Call) RunAndReturn(run func(context.Context, repository.InsertObjectParams) (repository.Mastercat, error)) *Repository_InsertObject_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAllObjects provides a mock function with given fields: _a0
func (_m *Repository) RemoveAllObjects(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAllObjects")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_RemoveAllObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllObjects'
type Repository_RemoveAllObjects_Call struct {
	*mock.Call
}

// RemoveAllObjects is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Repository_Expecter) RemoveAllObjects(_a0 interface{}) *Repository_RemoveAllObjects_Call {
	return &Repository_RemoveAllObjects_Call{Call: _e.mock.On("RemoveAllObjects", _a0)}
}

func (_c *Repository_RemoveAllObjects_Call) Run(run func(_a0 context.Context)) *Repository_RemoveAllObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_RemoveAllObjects_Call) Return(_a0 error) *Repository_RemoveAllObjects_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_RemoveAllObjects_Call) RunAndReturn(run func(context.Context) error) *Repository_RemoveAllObjects_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
