default:
	just --list

migrate db:
	migrate -database sqlite3://{{db}}.db -path internal/db/migrations up

build:
	go build -o build/main cmd/main.go

test:
	go test ./...

export CONFIG_PATH := env_var_or_default("CONFIG_PATH", "config.yaml")

run application flags='' $LOG_LEVEL="debug": build
	./build/main {{flags}} {{application}}

clean-build:
	rm -r build

clean-all:
	go clean
	go clean -testcache
	rm -r build

clean-db db:
	rm {{db}}.db

docs:
	swag init --dir ./ --generalInfo ./cmd/main.go --output ./docs
