default:
	just --list

migrate db:
	migrate -database sqlite3://{{db}}.db -path internal/db/migrations up

build: build-css
	go build -o build/main cmd/main.go

test:
	grc go test ./... -race

test-verbose:
	grc go test -v ./... -race

export CONFIG_PATH := env_var_or_default("CONFIG_PATH", "config.yaml")

run application flags='' $LOG_LEVEL="debug": build
	./build/main {{flags}} {{application}}

clean-build:
	rm -r build

clean-all:
	go clean
	go clean -testcache
	rm -r build

clean-db db:
	rm {{db}}.db

docs:
	swag init --dir ./ --generalInfo ./cmd/main.go --output ./docs

export USE_LOGGER := "true"
export ENVIRONMENT := "local"
export LOG_LEVEL := "debug"

live-server:
	air 

build-css-watch:
	tailwindcss --input ./ui/static/css/tailwind.css --output ./ui/static/css/output.css --watch --optimize --minify

build-css:
	tailwindcss --input ./ui/static/css/tailwind.css --output ./ui/static/css/output.css --optimize --minify
