package erosita

type InputSchema struct {
	IAUNAME           string  `parquet:"name=IAUNAME, type=BYTE_ARRAY"`
	DETUID            string  `parquet:"name=DETUID, type=BYTE_ARRAY"`
	SKYTILE           int32   `parquet:"name=SKYTILE, type=INT32"`
	ID_SRC            int32   `parquet:"name=ID_SRC, type=INT32"`
	UID               int64   `parquet:"name=UID, type=INT64"`
	UID_HARD          int64   `parquet:"name=UID_Hard, type=INT64"`
	ID_CLUSTER        int32   `parquet:"name=ID_CLUSTER, type=INT32"`
	RA                float64 `parquet:"name=RA, type=DOUBLE"`
	DEC               float64 `parquet:"name=DEC, type=DOUBLE"`
	RA_LOWERR         float32 `parquet:"name=RA_LOWERR, type=FLOAT"`
	RA_UPERR          float32 `parquet:"name=RA_UPERR, type=FLOAT"`
	DEC_LOWERR        float32 `parquet:"name=DEC_LOWERR, type=FLOAT"`
	DEC_UPERR         float32 `parquet:"name=DEC_UPERR, type=FLOAT"`
	POS_ERR           float32 `parquet:"name=POS_ERR, type=FLOAT"`
	MJD               float32 `parquet:"name=MJD, type=FLOAT"`
	MJD_MIN           float32 `parquet:"name=MJD_MIN, type=FLOAT"`
	MJD_MAX           float32 `parquet:"name=MJD_MAX, type=FLOAT"`
	EXT               float32 `parquet:"name=EXT, type=FLOAT"`
	EXT_ERR           float32 `parquet:"name=EXT_ERR, type=FLOAT"`
	EXT_LIKE          float32 `parquet:"name=EXT_LIKE, type=FLOAT"`
	DET_LIKE_0        float32 `parquet:"name=DET_LIKE_0, type=FLOAT"`
	ML_CTS_1          float32 `parquet:"name=ML_CTS_1, type=FLOAT"`
	ML_CTS_ERR_1      float32 `parquet:"name=ML_CTS_ERR_1, type=FLOAT"`
	ML_RATE_1         float32 `parquet:"name=ML_RATE_1, type=FLOAT"`
	ML_RATE_ERR_1     float32 `parquet:"name=ML_RATE_ERR_1, type=FLOAT"`
	ML_FLUX_1         float32 `parquet:"name=ML_FLUX_1, type=FLOAT"`
	ML_FLUX_ERR_1     float32 `parquet:"name=ML_FLUX_ERR_1, type=FLOAT"`
	ML_BKG_1          float32 `parquet:"name=ML_BKG_1, type=FLOAT"`
	ML_EXP_1          float32 `parquet:"name=ML_EXP_1, type=FLOAT"`
	APE_BKG_1         float32 `parquet:"name=APE_BKG_1, type=FLOAT"`
	APE_RADIUS_1      float32 `parquet:"name=APE_RADIUS_1, type=FLOAT"`
	APE_POIS_1        float32 `parquet:"name=APE_POIS_1, type=FLOAT"`
	DET_LIKE_P1       float32 `parquet:"name=DET_LIKE_P1, type=FLOAT"`
	ML_CTS_P1         float32 `parquet:"name=ML_CTS_P1, type=FLOAT"`
	ML_CTS_ERR_P1     float32 `parquet:"name=ML_CTS_ERR_P1, type=FLOAT"`
	ML_RATE_P1        float32 `parquet:"name=ML_RATE_P1, type=FLOAT"`
	ML_RATE_ERR_P1    float32 `parquet:"name=ML_RATE_ERR_P1, type=FLOAT"`
	ML_FLUX_P1        float32 `parquet:"name=ML_FLUX_P1, type=FLOAT"`
	ML_FLUX_ERR_P1    float32 `parquet:"name=ML_FLUX_ERR_P1, type=FLOAT"`
	ML_BKG_P1         float32 `parquet:"name=ML_BKG_P1, type=FLOAT"`
	ML_EXP_P1         float32 `parquet:"name=ML_EXP_P1, type=FLOAT"`
	APE_BKG_P1        float32 `parquet:"name=APE_BKG_P1, type=FLOAT"`
	APE_RADIUS_P1     float32 `parquet:"name=APE_RADIUS_P1, type=FLOAT"`
	APE_POIS_P1       float32 `parquet:"name=APE_POIS_P1, type=FLOAT"`
	DET_LIKE_P2       float32 `parquet:"name=DET_LIKE_P2, type=FLOAT"`
	ML_CTS_P2         float32 `parquet:"name=ML_CTS_P2, type=FLOAT"`
	ML_CTS_ERR_P2     float32 `parquet:"name=ML_CTS_ERR_P2, type=FLOAT"`
	ML_RATE_P2        float32 `parquet:"name=ML_RATE_P2, type=FLOAT"`
	ML_RATE_ERR_P2    float32 `parquet:"name=ML_RATE_ERR_P2, type=FLOAT"`
	ML_FLUX_P2        float32 `parquet:"name=ML_FLUX_P2, type=FLOAT"`
	ML_FLUX_ERR_P2    float32 `parquet:"name=ML_FLUX_ERR_P2, type=FLOAT"`
	ML_BKG_P2         float32 `parquet:"name=ML_BKG_P2, type=FLOAT"`
	ML_EXP_P2         float32 `parquet:"name=ML_EXP_P2, type=FLOAT"`
	APE_BKG_P2        float32 `parquet:"name=APE_BKG_P2, type=FLOAT"`
	APE_RADIUS_P2     float32 `parquet:"name=APE_RADIUS_P2, type=FLOAT"`
	APE_POIS_P2       float32 `parquet:"name=APE_POIS_P2, type=FLOAT"`
	DET_LIKE_P3       float32 `parquet:"name=DET_LIKE_P3, type=FLOAT"`
	ML_CTS_P3         float32 `parquet:"name=ML_CTS_P3, type=FLOAT"`
	ML_CTS_ERR_P3     float32 `parquet:"name=ML_CTS_ERR_P3, type=FLOAT"`
	ML_RATE_P3        float32 `parquet:"name=ML_RATE_P3, type=FLOAT"`
	ML_RATE_ERR_P3    float32 `parquet:"name=ML_RATE_ERR_P3, type=FLOAT"`
	ML_FLUX_P3        float32 `parquet:"name=ML_FLUX_P3, type=FLOAT"`
	ML_FLUX_ERR_P3    float32 `parquet:"name=ML_FLUX_ERR_P3, type=FLOAT"`
	ML_BKG_P3         float32 `parquet:"name=ML_BKG_P3, type=FLOAT"`
	ML_EXP_P3         float32 `parquet:"name=ML_EXP_P3, type=FLOAT"`
	APE_BKG_P3        float32 `parquet:"name=APE_BKG_P3, type=FLOAT"`
	APE_RADIUS_P3     float32 `parquet:"name=APE_RADIUS_P3, type=FLOAT"`
	APE_POIS_P3       float32 `parquet:"name=APE_POIS_P3, type=FLOAT"`
	DET_LIKE_P4       float32 `parquet:"name=DET_LIKE_P4, type=FLOAT"`
	ML_CTS_P4         float32 `parquet:"name=ML_CTS_P4, type=FLOAT"`
	ML_CTS_ERR_P4     float32 `parquet:"name=ML_CTS_ERR_P4, type=FLOAT"`
	ML_RATE_P4        float32 `parquet:"name=ML_RATE_P4, type=FLOAT"`
	ML_RATE_ERR_P4    float32 `parquet:"name=ML_RATE_ERR_P4, type=FLOAT"`
	ML_FLUX_P4        float32 `parquet:"name=ML_FLUX_P4, type=FLOAT"`
	ML_FLUX_ERR_P4    float32 `parquet:"name=ML_FLUX_ERR_P4, type=FLOAT"`
	ML_BKG_P4         float32 `parquet:"name=ML_BKG_P4, type=FLOAT"`
	ML_EXP_P4         float32 `parquet:"name=ML_EXP_P4, type=FLOAT"`
	APE_BKG_P4        float32 `parquet:"name=APE_BKG_P4, type=FLOAT"`
	APE_RADIUS_P4     float32 `parquet:"name=APE_RADIUS_P4, type=FLOAT"`
	APE_POIS_P4       float32 `parquet:"name=APE_POIS_P4, type=FLOAT"`
	DET_LIKE_P5       float32 `parquet:"name=DET_LIKE_P5, type=FLOAT"`
	ML_CTS_P5         float32 `parquet:"name=ML_CTS_P5, type=FLOAT"`
	ML_CTS_ERR_P5     float32 `parquet:"name=ML_CTS_ERR_P5, type=FLOAT"`
	ML_RATE_P5        float32 `parquet:"name=ML_RATE_P5, type=FLOAT"`
	ML_RATE_ERR_P5    float32 `parquet:"name=ML_RATE_ERR_P5, type=FLOAT"`
	ML_FLUX_P5        float32 `parquet:"name=ML_FLUX_P5, type=FLOAT"`
	ML_FLUX_ERR_P5    float32 `parquet:"name=ML_FLUX_ERR_P5, type=FLOAT"`
	ML_BKG_P5         float32 `parquet:"name=ML_BKG_P5, type=FLOAT"`
	ML_EXP_P5         float32 `parquet:"name=ML_EXP_P5, type=FLOAT"`
	APE_BKG_P5        float32 `parquet:"name=APE_BKG_P5, type=FLOAT"`
	APE_RADIUS_P5     float32 `parquet:"name=APE_RADIUS_P5, type=FLOAT"`
	APE_POIS_P5       float32 `parquet:"name=APE_POIS_P5, type=FLOAT"`
	DET_LIKE_P6       float32 `parquet:"name=DET_LIKE_P6, type=FLOAT"`
	ML_CTS_P6         float32 `parquet:"name=ML_CTS_P6, type=FLOAT"`
	ML_CTS_ERR_P6     float32 `parquet:"name=ML_CTS_ERR_P6, type=FLOAT"`
	ML_RATE_P6        float32 `parquet:"name=ML_RATE_P6, type=FLOAT"`
	ML_RATE_ERR_P6    float32 `parquet:"name=ML_RATE_ERR_P6, type=FLOAT"`
	ML_FLUX_P6        float32 `parquet:"name=ML_FLUX_P6, type=FLOAT"`
	ML_FLUX_ERR_P6    float32 `parquet:"name=ML_FLUX_ERR_P6, type=FLOAT"`
	ML_BKG_P6         float32 `parquet:"name=ML_BKG_P6, type=FLOAT"`
	ML_EXP_P6         float32 `parquet:"name=ML_EXP_P6, type=FLOAT"`
	APE_BKG_P6        float32 `parquet:"name=APE_BKG_P6, type=FLOAT"`
	APE_RADIUS_P6     float32 `parquet:"name=APE_RADIUS_P6, type=FLOAT"`
	APE_POIS_P6       float32 `parquet:"name=APE_POIS_P6, type=FLOAT"`
	FLAG_SP_SNR       int32   `parquet:"name=FLAG_SP_SNR, type=INT32"`
	FLAG_SP_BPS       int32   `parquet:"name=FLAG_SP_BPS, type=INT32"`
	FLAG_SP_SCL       int32   `parquet:"name=FLAG_SP_SCL, type=INT32"`
	FLAG_SP_LGA       int32   `parquet:"name=FLAG_SP_LGA, type=INT32"`
	FLAG_SP_GC_CONS   int32   `parquet:"name=FLAG_SP_GC_CONS, type=INT32"`
	FLAG_NO_RADEC_ERR int32   `parquet:"name=FLAG_NO_RADEC_ERR, type=INT32"`
	FLAG_NO_EXT_ERR   int32   `parquet:"name=FLAG_NO_EXT_ERR, type=INT32"`
	FLAG_NO_CTS_ERR   int32   `parquet:"name=FLAG_NO_CTS_ERR, type=INT32"`
	FLAG_OPT          int32   `parquet:"name=FLAG_OPT, type=INT32"`
}
