schema: spec-driven
rules:
  proposal:
    - Keep proposal as short as possible
  tasks:
    - Don't create a verification task at the end for running tests or building the code. Instead, include verification as an extra step on each task.
operations:
  apply:
    guidance:
      - Always implement only one task per session. Understand task as the whole set of steps for a top level number. Example, task 1 is composed by 1.1, 1.2 and 1.3
      - After the top level task is finished, stop all execution. The user will review the implemented code and possibly request changes
