/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/bulk-conesearch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk cone search for objects
     * @description Search for objects in a given region using multiple RA/Dec coordinates and a single radius.
     *     All coordinate pairs are searched in parallel for optimal performance.
     */
    post: operations["bulk-conesearch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulk-metadata": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk get metadata by object IDs
     * @description Retrieve detailed catalog metadata for multiple astronomical objects by their identifiers.
     *     All IDs are queried in parallel for optimal performance.
     */
    post: operations["bulk-metadata"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/conesearch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cone search for objects
     * @description Search for astronomical objects within a specified radius of given celestial coordinates (RA/Dec).
     *     Returns matching objects from the specified catalog.
     */
    get: operations["conesearch"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lightcurve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get lightcurve data
     * @description Retrieve time-series photometry data (lightcurve) for astronomical objects at the specified coordinates.
     *     Returns detections, non-detections, and forced photometry measurements.
     */
    get: operations["lightcurve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metadata": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get metadata by object ID
     * @description Retrieve detailed catalog metadata for a specific astronomical object by its identifier.
     */
    get: operations["metadata"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    "api.BulkConesearchRequest": {
      /**
       * @description Catalog name to search in (default: all)
       * @example allwise
       */
      catalog?: string;
      /**
       * @description Declination values in degrees (-90 to 90)
       * @example [
       *       -45,
       *       -45.5
       *     ]
       */
      dec?: number[];
      /**
       * @description Number of neighbors to return per coordinate (default: 1)
       * @example 1
       */
      nneighbor?: number;
      /**
       * @description Right ascension values in degrees (0-360)
       * @example [
       *       180.5,
       *       181.2
       *     ]
       */
      ra?: number[];
      /**
       * @description Search radius in degrees
       * @example 0.01
       */
      radius?: number;
    };
    "api.BulkMetadataRequest": {
      /**
       * @description Catalog to search in
       * @example allwise
       */
      catalog?: string;
      /**
       * @description List of object identifiers to search for
       * @example [
       *       "id1",
       *       "id2"
       *     ]
       */
      ids?: string[];
    };
    "conesearch.ValidationError": {
      errValue?: string;
      field?: string;
      reason?: string;
    };
    "lightcurve.Lightcurve": {
      detections?: unknown[];
      forced_photometry?: unknown[];
      non_detections?: unknown[];
    };
    "metadata.ValidationError": {
      field?: string;
      reason?: string;
      value?: string;
    };
    "repository.Allwise": {
      cntr?: number;
      h_m_2mass?: number;
      h_msig_2mass?: number;
      id?: string;
      j_m_2mass?: number;
      j_msig_2mass?: number;
      k_m_2mass?: number;
      k_msig_2mass?: number;
      w1mpro?: number;
      w1sigmpro?: number;
      w2mpro?: number;
      w2sigmpro?: number;
      w3mpro?: number;
      w3sigmpro?: number;
      w4mpro?: number;
      w4sigmpro?: number;
    };
    "repository.Mastercat": {
      cat?: string;
      dec?: number;
      id?: string;
      ipix?: number;
      ra?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "bulk-conesearch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Bulk conesearch request with arrays of coordinates */
    requestBody: {
      content: {
        "application/json": components["schemas"]["api.BulkConesearchRequest"];
      };
    };
    responses: {
      /** @description Found objects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["repository.Mastercat"][];
        };
      };
      /** @description No objects found */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Invalid parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["conesearch.ValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  "bulk-metadata": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Bulk metadata request with list of object IDs */
    requestBody: {
      content: {
        "application/json": components["schemas"]["api.BulkMetadataRequest"];
      };
    };
    responses: {
      /** @description Objects metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["repository.Allwise"][];
        };
      };
      /** @description No objects found */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Invalid parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["metadata.ValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  conesearch: {
    parameters: {
      query: {
        /**
         * @description Right Ascension (J2000) in degrees
         * @example 180.5
         */
        ra: number;
        /**
         * @description Declination (J2000) in degrees
         * @example -45
         */
        dec: number;
        /**
         * @description Search radius in degrees
         * @example 0.01
         */
        radius: number;
        /** @description Catalog to search in */
        catalog?: string;
        /** @description Maximum number of neighbors to return */
        nneighbor?: number;
        /** @description Include full metadata in response */
        getMetadata?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Found objects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["repository.Mastercat"][];
        };
      };
      /** @description No objects found */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Invalid parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["conesearch.ValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  lightcurve: {
    parameters: {
      query: {
        /**
         * @description Right Ascension (J2000) in degrees
         * @example 180.5
         */
        ra: number;
        /**
         * @description Declination (J2000) in degrees
         * @example -45
         */
        dec: number;
        /**
         * @description Search radius in arcseconds
         * @example 5
         */
        radius: number;
        /** @description Number of neighbors to return */
        nneighbor?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lightcurve data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["lightcurve.Lightcurve"];
        };
      };
      /** @description Invalid parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  metadata: {
    parameters: {
      query: {
        /**
         * @description Object identifier
         * @example J120000.00-450000.0
         */
        id: string;
        /**
         * @description Catalog to search in
         * @example allwise
         */
        catalog: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Object metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["repository.Allwise"];
        };
      };
      /** @description Object not found */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Invalid parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["metadata.ValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
}
