// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Diego Rodriguez Mancini",
            "email": "diegorodriguezmancini@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bulk-conesearch": {
            "post": {
                "description": "Search for objects in a given region using lists of ra, dec and a single radius. Radius is in arcseconds. Results are grouped by catalog.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conesearch"
                ],
                "summary": "Search for objects in a given region using multiple coordinates",
                "parameters": [
                    {
                        "description": "Bulk conesearch request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.BulkConesearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/conesearch.MastercatResult"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/conesearch.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/bulk-metadata": {
            "post": {
                "description": "Search for metadata by multiple ids in bulk. The response fields depend on the requested catalog (allwise, gaia or erosita) and include the catalog-specific columns plus ra and dec.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metadata"
                ],
                "summary": "Search for metadata by multiple ids",
                "parameters": [
                    {
                        "description": "Bulk metadata request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.BulkMetadataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Catalog-specific metadata records",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/metadata.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/conesearch": {
            "get": {
                "description": "Search for objects in a given region using ra, dec and radius. Radius is in arcseconds. Returns mastercat results grouped by catalog, or metadata results grouped by catalog when getMetadata is true.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conesearch"
                ],
                "summary": "Search for objects in a given region",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Right ascension in degrees",
                        "name": "ra",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Declination in degrees",
                        "name": "dec",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Radius in arcseconds",
                        "name": "radius",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Catalog to search in (default: all)",
                        "name": "catalog",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Number of neighbors to return (default: 1)",
                        "name": "nneighbor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Return metadata results instead of mastercat results (default: false)",
                        "name": "getMetadata",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/conesearch.MastercatResult"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/conesearch.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/lightcurve": {
            "get": {
                "description": "Get lightcurve data for specified coordinates with search radius and neighbor count",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lightcurve"
                ],
                "summary": "Get lightcurve data for coordinates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Right Ascension coordinate",
                        "name": "ra",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Declination coordinate",
                        "name": "dec",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search radius in arcseconds",
                        "name": "radius",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Catalog to query: all, ztf, neowise or allwise (default: all)",
                        "name": "catalog",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Number of neighbors to return (default: 1)",
                        "name": "nneighbor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LightcurveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ParseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metadata": {
            "get": {
                "description": "Search for metadata by id. The response fields depend on the requested catalog (allwise, gaia or erosita) and include the catalog-specific columns plus ra and dec.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metadata"
                ],
                "summary": "Search for metadata by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID to search for",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Catalog to search in (allwise, gaia or erosita)",
                        "name": "catalog",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Catalog-specific metadata record",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/metadata.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.BulkConesearchRequest": {
            "type": "object",
            "properties": {
                "catalog": {
                    "type": "string"
                },
                "dec": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "nneighbor": {
                    "type": "integer"
                },
                "ra": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "radius": {
                    "type": "number"
                }
            }
        },
        "api.BulkMetadataRequest": {
            "type": "object",
            "properties": {
                "catalog": {
                    "type": "string"
                },
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.LightcurveEntry": {
            "type": "object",
            "properties": {
                "catalog": {
                    "type": "string"
                },
                "data": {
                    "type": "object"
                },
                "id": {
                    "type": "string"
                },
                "mag": {
                    "type": "number"
                },
                "magerr": {
                    "type": "number"
                },
                "mjd": {
                    "type": "number"
                },
                "object_id": {
                    "type": "string"
                }
            }
        },
        "api.LightcurveResponse": {
            "type": "object",
            "properties": {
                "detections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.LightcurveEntry"
                    }
                },
                "forced_photometry": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.LightcurveEntry"
                    }
                },
                "non_detections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.LightcurveEntry"
                    }
                }
            }
        },
        "api.ParseError": {
            "type": "object",
            "properties": {
                "ErrValue": {
                    "type": "string"
                },
                "Field": {
                    "type": "string"
                },
                "Reason": {
                    "type": "string"
                }
            }
        },
        "conesearch.MastercatExtended": {
            "type": "object",
            "properties": {
                "cat": {
                    "type": "string"
                },
                "dec": {
                    "type": "number"
                },
                "distance": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "ipix": {
                    "type": "integer"
                },
                "ra": {
                    "type": "number"
                }
            }
        },
        "conesearch.MastercatResult": {
            "type": "object",
            "properties": {
                "catalog": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/conesearch.MastercatExtended"
                    }
                },
                "index": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_in_catalog": {
                    "type": "integer"
                }
            }
        },
        "conesearch.ValidationError": {
            "type": "object",
            "properties": {
                "ErrValue": {
                    "type": "string"
                },
                "Field": {
                    "type": "string"
                },
                "Reason": {
                    "type": "string"
                }
            }
        },
        "metadata.ValidationError": {
            "type": "object",
            "properties": {
                "Field": {
                    "type": "string"
                },
                "Reason": {
                    "type": "string"
                },
                "Value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "CrossWave HTTP API",
	Description:      "API for the CrossWave Xmatch service. This service allows to search for objects in a given region and to retrieve metadata from the catalogs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
