name: Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache-dependency-path: service/go.mod
          
      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v14
        with:
          name: xmatch
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Install devenv.sh
        run: |
          nix profile install nixpkgs#devenv

      - name: Run the tests
        run: nix develop --no-pure-eval --accept-flake-config --command devenv test
