name: Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: |
          nix profile install nixpkgs#devenv
      - uses: HatsuneMiku3939/direnv-action@v1
      - name: Run tests
        run: |
          cd healpix && ./run_swig.sh
          cd ../service
          just test

