CREATE TABLE IF NOT EXISTS gaia (
    id text not null,
    source_id bigint,
    ra_error double precision,
    dec_error double precision,
    parallax double precision,
    parallax_error double precision,
    pm double precision,
    pmra double precision,
    pmra_error double precision,
    pmdec double precision,
    pmdec_error double precision,
    astrometric_excess_noise double precision,
    astrometric_excess_noise_sig double precision,
    ruwe double precision,
    phot_g_n_obs integer,
    phot_g_mean_flux double precision,
    phot_g_mean_flux_error double precision,
    phot_g_mean_flux_over_error double precision,
    phot_g_mean_mag double precision,
    phot_bp_n_obs integer,
    phot_bp_mean_flux double precision,
    phot_bp_mean_flux_error double precision,
    phot_bp_mean_flux_over_error double precision,
    phot_bp_mean_mag double precision,
    phot_rp_n_obs integer,
    phot_rp_mean_flux double precision,
    phot_rp_mean_flux_error double precision,
    phot_rp_mean_flux_over_error double precision,
    phot_rp_mean_mag double precision,
    phot_bp_rp_excess_factor double precision,
    phot_proc_mode integer,
    bp_rp double precision,
    bp_g double precision,
    g_rp double precision,
    radial_velocity double precision,
    radial_velocity_error double precision,
    rv_method_used integer,
    phot_variable_flag text,
    in_qso_candidates integer,
    in_galaxy_candidates integer,
    non_single_star integer,
    has_epoch_photometry integer,
    classprob_dsc_combmod_quasar double precision,
    classprob_dsc_combmod_galaxy double precision,
    classprob_dsc_combmod_star double precision,
    teff_gspphot double precision,
    teff_gspphot_lower double precision,
    teff_gspphot_upper double precision,
    logg_gspphot double precision,
    logg_gspphot_lower double precision,
    logg_gspphot_upper double precision,
    mh_gspphot double precision,
    mh_gspphot_lower double precision,
    mh_gspphot_upper double precision,
    distance_gspphot double precision,
    distance_gspphot_lower double precision,
    distance_gspphot_upper double precision,
    PRIMARY KEY (id)
)
